### ISSUE TITLE
Null check is not using isnull function instead checking = 'NULL'.

### ISSUE THREAD

**Issue by ted-ks** [timgws/QueryBuilderParser#10]
```
$json = '{
  "condition": "OR",
  "rules": [
    {
      "id": "t_o",
      "field": "t_o",
      "type": "integer",
      "input": "text",
      "operator": "equal",
      "value": "0"
    },
    {
      "id": "t_o",
      "field": "t_o",
      "type": "integer",
      "input": "text",
      "operator": "is_null",
      "value": null
    }
  ]
}';
		$c = DB::table('c');
		
		$qbp = new QueryBuilderParser(
				array( 't_o', 'i_o')
		);
		
		$query = $qbp->parse($json, $c);
		
		error_log($query->toSql());
		
		$rows = $query->get();
```

For the above query generated is 

_select * from `c` where `t_o` = '0' or `t_o` = 'NULL';_ which was not returning the expected out put - I was expecting the query to be generated like following -
_select * from `c` where `t_o` = '0' or isnull(`t_o`);_

Please correct me If I am wrong in my assumption. Thanks

**Comment by timgws** [comment]
Yeah, I can see that now. I am writing a test now and finding out where the issue is.

**Comment by timgws** [comment]
Thanks for reporting this. This issue is now resolved 👍
