### ISSUE TITLE
JoinSupportingQueryBuilderParser always return AND even if OR is the condition

### ISSUE THREAD

**Issue by milhouse1337** [timgws/QueryBuilderParser#13]
Hi there,

First of all this is a great stuff, thank you for this.

I noticed a small bug, when I select OR in the QueryBuilder the parser always seperate them with AND instead of OR statements.

Here is an example query output:

> select \* from table where exists (...) **and** exists (...)

Not sure but I think it comes from this:
https://github.com/timgws/QueryBuilderParser/blob/master/src/QueryBuilderParser/JoinSupportingQueryBuilderParser.php#L117

I will try to make a test for this case later.

Thank you!

**Comment by timgws** [comment]
Ah, good point @milhouse1337, thanks for pointing that out.

Feel free to add a PR for a fix (please also add a test case, so this doesn't happen again!)

**Comment by timgws** [comment]
Thanks! This has been fixed @milhouse1337

**Comment by milhouse1337** [comment]
Great, thank you so much! :)
