### ISSUE TITLE
JoinSupportingQueryBuilderParser is not working with "is_null" operator

### ISSUE THREAD

**Issue by milhouse1337** [timgws/QueryBuilderParser#14]
Hi,

I added the `is_null` operator on the QueryBuilder but it seems to be parsed like a value, the resulting SQL query looks like:
`... field_name = "NULL" ...`

but it should be like this:
`... field_name IS NULL ...`

I will try to make a test with this case in a few days.

Thank you again!

**Comment by timgws** [comment]
Thanks @milhouse1337

**Comment by milhouse1337** [comment]
I just forked it and made a fix. Do you want me to make a PR ?

Thank you!

**Comment by timgws** [comment]
Hey @milhouse1337, I just saw this comment, sorry for not replying sooner!

I think `buildSubclauseWithNull` and `buildSubclauseWithNotNull` could potentially be merged, where a parameter states whether the clause is `null` or `!null` (`$isNull`?).

ie, the signature of `buildSubclauseWithNull` would change to:

```
buildSubclauseWithNull($subclause, Builder $query, $isNull = true)
```

and an if statement is put in the function, something along the lines of:

```
    private function buildSubclauseWithNull($subclause, Builder $query, $is_null = true)
    {
        if ($is_null === false)
            return $query->whereNotNull($subclause['to_value_column']);

        return $query->whereNull($subclause['to_value_column']);
    }
```

Just as I was writing this, I think this might already be in QBPFunctions.php: https://github.com/timgws/QueryBuilderParser/blob/8bf4cdffa0b95a3aa73afa578b1f0fcd12e3ef9b/src/QueryBuilderParser/QBPFunctions.php#L263-L283

**Comment by milhouse1337** [comment]
I just updated the fix, thank you again!

**Comment by timgws** [comment]
This is perfect, thanks @milhouse1337.

I will merge in the next hour or so.

**Comment by timgws** [comment]
@milhouse1337 can you please make a Pull Request for this?

**Comment by milhouse1337** [comment]
Thank you for the merge!
