### ISSUE TITLE
Laravel 5.4 Support

### ISSUE THREAD

**Issue by Andi82ka** [timgws/QueryBuilderParser#16]
Hey,

just wanted to Upgrade to Laravel 5.4 but it is blocked by QueryBuilderParser. I saw that you made the required changes already.

When there will be a release?

Best regards

**Comment by timgws** [comment]
In one day. Sorry for not getting the release to you sooner. 

It might not be a bad idea to run dev-master, seeing as most the functionality is stable, and I don't see the api changing any time soon.
