### ISSUE TITLE
Only JS version

### ISSUE THREAD

**Issue by prashantguleria** [timgws/QueryBuilderParser#24]
Hi,

Is it possible to have it pure JS/jQuery based.
I want to use it with C# but I need ot have joins functionaity.

Thanks

**Comment by timgws** [comment]
You might want to check out https://github.com/castle-it/dynamic-linq-query-builder

Also, the QueryBuilder supports building SQL queries in Javascript (http://querybuilder.js.org/demo.html#import_export)

**Comment by prashantguleria** [comment]
Thanks for the reply.

I'm currently using castle-it LINQ builder but it's not capable of complex queries like JOINS and aggregate functions.

**Comment by timgws** [comment]
You should think about adding that functionality there to that project! This is a PHP project, so it is outside of this library's scope to work with C# :)

I'm sure the author would appreciate a pull request with that functionality!
