### ISSUE TITLE
Can't install on 5.7

### ISSUE THREAD

**Issue by kjjdion** [timgws/QueryBuilderParser#36]
Can't composer require this for 5.7, get this error:

`timgws/query-builder-parser 1.5 requires illuminate/database 4.1 - 5.6`

Possible to push your 5.8 changes? Or at least just the composer file to allow 5.7.* in the meantime?

**Comment by kjjdion** [comment]
Won't let me install 1.5.1 even if I do: 

`"timgws/query-builder-parser": "^1.5.1"`

I get this:

`The requested package timgws/query-builder-parser ^1.5.1 exists as timgws/query-builder-parser[1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2, 1.3, 1.4, 1.5, dev-master, v1.0] but these are rejected by your constraint.`

**Comment by timgws** [comment]
Could you try running:

```
composer clearcache
```

followed by:

```
composer require timgws/query-builder-parser ^1.5.1
composer why timgws/query-builder-parser ^1.5.1
composer why-not timgws/query-builder-parser ^1.5.1
```

and let me know what the output is?

**Comment by timgws** [comment]
Note that 5.8 changes were pushed 5 days ago.

https://github.com/timgws/QueryBuilderParser/releases/tag/1.5.1

https://github.com/timgws/QueryBuilderParser/commit/e8ff09ca5bc038b7d20e12ff4053f1e503ee25ae

**Comment by kjjdion** [comment]
Works now :)
