### ISSUE TITLE
Example with DataTables

### ISSUE THREAD

**Issue by p0nt** [timgws/QueryBuilderParser#47]
Is there a working example in combination with datatables somewhere? Laravel version 6^

**Comment by timgws** [comment]
https://github.com/timgws/QueryBuilderParser#integration-examplesIt would be relatively easy to migrate this example to yajrahttps://github.com/yajra/laravel-datatables#jquery-datatables-api-for-laravel-4567 ---- On Sat, 25 Jul 2020 09:03:08 +1000  notifications@github.com  wrote ----
Is there a working example in combination with datatables somewhere? Laravel version 6^

**Comment by p0nt** [comment]
Hi Tim,

Thanks for the quick reply. So I do not understand where $input comes from in that example code.

Also the use of ::Input is not allowed anymore since its replaced by Requests.

Is $querybuilderJSON actual row data from MySQL formatted as JSON? 

So what should be inside $input[‘querybuilder’] then?
