### ISSUE TITLE
Query AND/OR condition is being parsed incorrectly

### ISSUE THREAD

**Issue by simplesi** [timgws/QueryBuilderParser#5]
```QueryBuilderParserTest::testMoreComplexQuery()``` asserts that this JSON:
```
{
       "condition":"AND",
       "rules":[
          {
             "id":"price",
             "field":"price",
             "type":"double",
             "input":"text",
             "operator":"less",
             "value":"10.25"
          },
          {
             "condition":"OR",
             "rules":[
                {
                   "id":"name",
                   "field":"name",
                   "type":"string",
                   "input":"text",
                   "operator":"begins_with",
                   "value":"Thommas"
                },
                {
                   "id":"name",
                   "field":"name",
                   "type":"string",
                   "input":"text",
                   "operator":"equal",
                   "value":"John Doe"
                }
             ]
          }
       ]
    }
```
parses as:
```select * where `price` < ? OR (`name` LIKE ? and `name` = ?)```

This isn't correct - it should actually be:
```select * where `price` < ? AND (`name` LIKE ? OR `name` = ?)```

The condition should be taken from the array holding a given set of rules, not from the first nested rule.

You can confirm this by forming a similar query in the QueryBuilder demo page: http://querybuilder.js.org/demo.html#import_export
<img width="688" alt="screen shot 2015-09-22 at 17 49 30" src="https://cloud.githubusercontent.com/assets/384302/10025092/59906020-6152-11e5-9d01-002fe52a95db.png">

and then rendering to SQL using the SQL plugin:
```name = 'a' AND ( in_stock = 0 OR price = 3 )```

I will put together a PR to fix this, but it's definitely going to be a breaking change to what you currently have.

**Comment by timgws** [comment]
Hi @simplesi, as per #6, please pull the latest dev-master from this repository.

**Comment by simplesi** [comment]
Yes, absolutely - sorry, I've been busy with other things and so haven't got to this yet. I will do soon!
