### ISSUE TITLE
JoinSupportingQueryBuilderParser

### ISSUE THREAD

**Issue by jeffmbalicki** [timgws/QueryBuilderParser#50]
Should this:

```
$table = DB::table('table_of_data_to_integrate');
$jsqbp = new JoinSupportingQueryBuilderParser($fields, $this->getJoinFields());
$test = $parser->parse($json, $builder);
```

Actually be this:

```
$table = DB::table('table_of_data_to_integrate');
$jsqbp = new JoinSupportingQueryBuilderParser($fields, $this->getJoinFields());
$test = $jsqbp->parse($json, $table);
```

**Comment by timgws** [comment]
Yes! Good catch.  ---- On Fri, 02 Apr 2021 04:40:53 +1100  ***@***.***  wrote ----
Should this:
 $table = DB::table('table_of_data_to_integrate'); $jsqbp = new JoinSupportingQueryBuilderParser($fields, $this->getJoinFields()); $test = $parser->parse($json, $builder);
Actually be this:
 $table = DB::table('table_of_data_to_integrate'); $jsqbp = new JoinSupportingQueryBuilderParser($fields, $this->getJoinFields()); $test = $jsqbp->parse($json, $table);
