### ISSUE TITLE
mongoDB aggregation

### ISSUE THREAD

**Issue by GlauberF** [timgws/QueryBuilderParser#51]
hello, I would like to know if it is possible to join (aggregate) for mongoDB?
Because the library is very nice, but to use it on a day-to-day basis, I need to be able to do aggregation for mongoDB.

Or if it is not possible to join (aggregate) for mongoDB with the library, if you have any alternative to be able to do it.

**Comment by timgws** [comment]
Can you please explain what data and how you want to build your aggregation?

As mentioned in the documentation, this query builder will just use `jenssegers/mongodb`, and aggregations are supported. Have you tried using the `JoinSupportingQueryBuilderParser`?

**Comment by GlauberF** [comment]
Solved, sory.
